### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by 0rdinal** [cokwa/F4MP#1]
Hey man, I was wondering. Obviously this is still in heavy development, but if you could leave instructions on how someone could compile and try this out on their own machine, that'd be amazing. 

I also suggest leaving your github on your videos so people can find it easier.

**Comment by Sturlen** [comment]
I agree with you on both points. This seems to be a very interesting project, and a note on how to compile it would be very nice.

**Comment by ZombieRoxtar** [comment]
I just got it to compile. The problem that had was in the common_vc11 project with common\IPrefix.h. It had the Windows version (_WIN32_WINNT) defined as 0x0501 (XP) and Cokwa's third party code doesn't compile unless it is at at least 0x0601 (Win 7). Since there may be other stuff like that, I just used Win 10 and it worked.

common\IPrefix.h:14
`#define _WIN32_WINNT 0x0A00 // Windows 10`

**Comment by Hirado6** [comment]
@ZombieRoxtar it would be very nice if you could upload the finished compiled file.

**Comment by ZombieRoxtar** [comment]
Good idea, @Hirado6.  I also compiled the pex scripts, but the furthest I ever got with them was typing `cgf "f4mp.connect"` into the console to crash the game. None of the parameters that I tried seemed to appease it and I don't really speak Papyrus. It would be very nice for someone to outline the basics of getting a game connected.

[f4mp_bin.zip](https://github.com/cokwa/F4MP/files/4830531/f4mp_bin.zip)

**Comment by SebastianRoger** [comment]
Howdy folks, according to Hyunsung Go, the github is missing an ESP file, he forgot to upload it. So, without that, we can't do anything.

**Comment by cokwa** [comment]
Do you guys want it? Shall I just upload it now? 'Cause I'm planning to get rid of it completely.

**Comment by SebastianRoger** [comment]
I would if you would be willing to share it

**Comment by cokwa** [comment]
https://drive.google.com/file/d/1zn-bJSLLR-Na3dGdhlRl2lTsbglLvBa9/view?usp=sharing
Here, I don't want to put it on GitHub for now. So instead here's a Google Drive link.

**Comment by SebastianRoger** [comment]
Thank you very much, can you shortly explain how to connect?

**Comment by cokwa** [comment]
If you start up the game first time with this mod, you would have a file: "Documents/My Games/Fallout 4/F4MP/config.txt".
This is the file you type in the IP address of the host.
After editing and saving the configuration file, you start up the game with the mod active.
And you load up a save file. After the loading is done, you press the F1 key to connect to the server.
It might take a minute or so because of the shitty dialogue sync. But you'd eventually end up connected successfully to the server.
Do this on another PC, you'd see each other.
Keep in mind there's a bunch of code for debugging and it might be a mess because I haven't done any extensive testing.

**Comment by SebastianRoger** [comment]
Thank you very much! Just to clarify quickly, do I put my localip address into the serverconfig? Because putting my external there just causes it to crash

**Comment by cokwa** [comment]
I guess? I'm not entirely sure.

**Comment by Hirado6** [comment]
@RyuTheRyu i think you need your ipv4  adresse to connect and could you maybe explain me how i install the mod and where i have to insert the ESP File ?

**Comment by SebastianRoger** [comment]
@Hirado6 you put the prebuilt mod, built by @ZombieRoxtar in the Fallout 4 basedir, put the ESP in the /data/ folder.

**Comment by 0rdinal** [comment]
config.txt doesn't appear for me. Both Using NMM or putting it in the /data/ folder didn't seem to do it for me

**Comment by cokwa** [comment]
@Genetical Are you sure you put f4mp.dll in the right place? config.txt doesn't even have anything to do with the esp file, I think.

**Comment by ZombieRoxtar** [comment]
It worked for me like @cokwa described. @Genetical, if your game spawns a second black window when it starts then the config file is probably there. (If not, then you're not using f4se_loader or the DLL is in the wrong place.) Try pasting this into a Windows Run box. `"%userprofile%\Documents\My Games\Fallout4\F4MP"`. For me, that folder has a log file and the config file. I had a linked game between my gaming computer and my spare. It's slow and buggy, but the functionality is there and I hope someone can run with this.
We really need to not make this a tech support thread, though.
It works when you can can get the pex, dll, and esp files in the right places. Make your config.txt point to the local (192) address of the machine where the server is running. Start that and then start the game via F4SE.

**Comment by SebastianRoger** [comment]
That's true. Most of the points of the OP have been addressed, shouldn't this thread be closed?

**Comment by 0rdinal** [comment]
It was an error on my end. OP has answered. Closing the issue
